# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'hamimp/web_app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      '$(Build.BuildNumber)'
      latest

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'hamim-aks'
    azureResourceGroup: 'hamim-aks-network-rg'
    kubernetesCluster: 'hamim-aks-cluster'
    manifests: 'application-manifest.yaml'
